org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.3.27
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=riftwind
mod_name=Riftwind
mod_license=WTFPL
mod_version=forge-1.20.1-1.0.1
mod_group_id=com.teampotato.riftwind
mod_authors=Kasualix

# Proxy
# REMOVE THIS IF YOU WANT TO BUILD THIS PROJECT BY YOURSELF
    systemProp.http.proxyHost=localhost
    systemProp.http.proxyPort=7890
    systemProp.https.proxyHost=localhost
    systemProp.https.proxyPort=7890