org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

minecraft_version=1.16.5
minecraft_version_range=[1.16.5,1.17)
forge_version=36.2.42
forge_version_range=[36,)
loader_version_range=[36,)
mapping_channel=official
mapping_version=1.16.5

mod_id=riftwind
mod_name=Riftwind
mod_license=WTFPL
mod_version=forge-1.16.5-1.0.1
mod_group_id=com.teampotato.riftwind
mod_authors=Kasualix

# Proxy
# REMOVE THIS IF YOU WANT TO BUILD THIS PROJECT BY YOURSELF
    systemProp.http.proxyHost=localhost
    systemProp.http.proxyPort=7890
    systemProp.https.proxyHost=localhost
    systemProp.https.proxyPort=7890